services:
  mc-router:
    image: itzg/mc-router
    container_name: mc-router
    labels:
      app.kubos.dev/component: mc-router
    environment:
      PORT: 25565
      ROUTES_CONFIG: /config/routes.json
    volumes:
      - ${MC_ROUTER_HOST_CONFIG_DIR:-/var/lib/mc-auto-starting/shared/mc-router}:/config
    ports:
      - ${MINECRAFT_PUBLIC_PORT:-25565}:25565"
    restart: unless-stopped
    networks:
      - mc_router_net

networks:
  mc_router:
    name: mc_router_net
    external: true
