<%
require "uri"
app_base_url = ENV.fetch("APP_BASE_URL")
app_uri = URI.parse(app_base_url)
%>
servers:
  web:
    hosts:
      - <%= ENV.fetch("DEPLOY_WEB_HOST") %>

proxy:
  host: <%= app_uri.host %>
  ssl: <%= app_uri.scheme == "https" %>
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3
    timeout: 5
