service: mc-auto-starting
image: <%= ENV.fetch("KAMAL_IMAGE") %>
require_destination: true
hooks_path: .kamal/hooks
secrets_path: .kamal/secrets
asset_path: /rails/public/assets

registry:
  server: <%= ENV.fetch("KAMAL_REGISTRY_SERVER", "docker.io") %>
  username: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: <%= ENV.fetch("RAILS_LOG_LEVEL", "info") %>
    DB_HOST: <%= ENV.fetch("DB_HOST") %>
    DB_PORT: <%= ENV.fetch("DB_PORT", "3306") %>
    DB_NAME_PRODUCTION: <%= ENV.fetch("DB_NAME_PRODUCTION", "app_production") %>
    REDIS_URL: redis://mc-auto-starting-redis:6379/1
    MINECRAFT_PUBLIC_DOMAIN: <%= ENV.fetch("MINECRAFT_PUBLIC_DOMAIN") %>
    MINECRAFT_PUBLIC_PORT: <%= ENV.fetch("MINECRAFT_PUBLIC_PORT") %>
    APP_BASE_URL: <%= ENV.fetch("APP_BASE_URL") %>
  secret:
    - RAILS_MASTER_KEY
    - APP_DATABASE_PASSWORD:DB_PASSWORD
    - DB_USERNAME
    - DISCORD_CLIENT_ID
    - DISCORD_CLIENT_SECRET
    - DISCORD_BOT_API_TOKEN
    - MINECRAFT_RCON_PASSWORD_SECRET

volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/lib/mc-auto-starting/shared/mc-router:/rails/shared/mc-router
  - /var/lib/mc-auto-starting/shared/storage:/rails/storage

accessories:
  redis:
    service: mc-auto-starting-redis
    image: redis:7
    roles:
      - web
    directories:
      - /var/lib/mc-auto-starting/accessories/redis:/data
